# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import image_login_pic_rc

class Ui_Login_Ui_Form(object):
    def setupUi(self, Login_Ui_Form):
        Login_Ui_Form.setObjectName("Login_Ui_Form")
        Login_Ui_Form.resize(1019, 595)
        self.centralwidget = QtWidgets.QWidget(Login_Ui_Form)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 671, 531))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/login/image/login_main.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(700, 10, 301, 131))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/login/image/hkustMain_logo.png"))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(710, 180, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(710, 240, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(710, 290, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(710, 340, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(710, 160, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(710, 220, 72, 15))
        self.label_4.setObjectName("label_4")
        Login_Ui_Form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Login_Ui_Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 26))
        self.menubar.setObjectName("menubar")
        Login_Ui_Form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Login_Ui_Form)
        self.statusbar.setObjectName("statusbar")
        Login_Ui_Form.setStatusBar(self.statusbar)

        self.retranslateUi(Login_Ui_Form)
        QtCore.QMetaObject.connectSlotsByName(Login_Ui_Form)

    def retranslateUi(self, Login_Ui_Form):
        _translate = QtCore.QCoreApplication.translate
        Login_Ui_Form.setWindowTitle(_translate("Login_Ui_Form", "Login Window"))
        self.pushButton.setText(_translate("Login_Ui_Form", "Sign in"))
        self.pushButton_2.setText(_translate("Login_Ui_Form", "Sign up"))
        self.label_3.setText(_translate("Login_Ui_Form", "Username"))
        self.label_4.setText(_translate("Login_Ui_Form", "Password"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login_Ui_Form = QtWidgets.QMainWindow()
    ui = Ui_Login_Ui_Form()
    ui.setupUi(Login_Ui_Form)
    Login_Ui_Form.show()
    sys.exit(app.exec_())
