# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yoloui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Yolowindow(object):
    def setupUi(self, Yolowindow):
        Yolowindow.setObjectName("Yolowindow")
        Yolowindow.resize(1019, 620)
        Yolowindow.setStyleSheet(
                'background-image: url(":/login/image/login_main_tr.png") 0 0 0 0 stretch stretch')
        self.centralwidget = QtWidgets.QWidget(Yolowindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 10, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 40, 801, 431))
        self.label_3.setStyleSheet("")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(5, 380, 181, 171))
        self.textBrowser.setObjectName("textBrowser")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 350, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(18)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 270, 171, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(550, 500, 101, 51))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(900, 500, 101, 51))
        self.pushButton_5.setStyleSheet("background-color:rgb(255, 97, 35)")
        self.pushButton_5.setObjectName("pushButton_5")
        self.ComboBox_weight = QtWidgets.QFontComboBox(self.centralwidget)

        self.ComboBox_weight.setGeometry(QtCore.QRect(10, 50, 171, 21))
        self.ComboBox_weight.setEditable(True)
        self.ComboBox_weight.setModelColumn(0)
        self.ComboBox_weight.setObjectName("ComboBox_weight")
        self.ComboBox_weight.clear()
        self.ComboBox_weight.addItems(
                ["yolov5n", "yolov5s", "yolov5m", "yolov5l", "yolov5x", "exp26-last", "exp22-last", "exp16-last"])

        self.ComboBox_model = QtWidgets.QFontComboBox(self.centralwidget)
        self.ComboBox_model.setGeometry(QtCore.QRect(10, 80, 171, 22))
        self.ComboBox_model.setObjectName("ComboBox_model")
        self.ComboBox_model.clear()
        self.ComboBox_model.addItems(
                ["coco128", "Argoverse", "coco", "GlobalWheat2020", "Objects365", "SKU-110K", "VOC", "xView"])





        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(210, 500, 101, 51))
        self.pushButton_6.setStyleSheet("background-color:rgb(106, 253, 143)")
        self.pushButton_6.setObjectName("pushButton_6")

        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(60, 130, 121, 22))
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(100)
        self.horizontalSlider.setProperty("value", 25)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")

        self.horizontalSlider_2 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(60, 180, 121, 22))
        self.horizontalSlider_2.setMinimum(1)
        self.horizontalSlider_2.setMaximum(100)
        self.horizontalSlider_2.setProperty("value", 45)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(60, 230, 121, 22))
        self.horizontalSlider_3.setMinimum(1)
        self.horizontalSlider_3.setMaximum(30)
        self.horizontalSlider_3.setProperty("value", 30)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(10, 130, 51, 22))
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setProperty("value", 0.25)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(10, 230, 51, 22))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(30)
        self.spinBox.setProperty("value", 30)
        self.spinBox.setObjectName("spinBox")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 171, 16))
        self.label_5.setObjectName("label_5")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(10, 180, 51, 22))
        self.doubleSpinBox_2.setMaximum(1.0)
        self.doubleSpinBox_2.setSingleStep(0.01)
        self.doubleSpinBox_2.setProperty("value", 0.45)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 160, 171, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 210, 31, 16))
        self.label_7.setObjectName("label_7")
        Yolowindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Yolowindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 26))
        self.menubar.setObjectName("menubar")
        Yolowindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Yolowindow)
        self.statusbar.setObjectName("statusbar")
        Yolowindow.setStatusBar(self.statusbar)

        self.retranslateUi(Yolowindow)
        QtCore.QMetaObject.connectSlotsByName(Yolowindow)

    def retranslateUi(self, Yolowindow):
        _translate = QtCore.QCoreApplication.translate
        Yolowindow.setWindowTitle(_translate("Yolowindow", "Yolov5 Window"))
        self.label.setText(_translate("Yolowindow", "Settings"))
        self.label_2.setText(_translate("Yolowindow", "Video Frame"))
        self.label_4.setText(_translate("Yolowindow", "Results"))
        self.pushButton_3.setText(_translate("Yolowindow", "Reset"))
        self.pushButton_4.setText(_translate("Yolowindow", "Pause"))
        self.pushButton_5.setText(_translate("Yolowindow", "Stop"))
        self.ComboBox_weight.setCurrentText(_translate("Yolowindow", "Model"))
        self.ComboBox_model.setCurrentText(_translate("Yolowindow", "Data"))
        self.pushButton_6.setText(_translate("Yolowindow", "Start"))
        self.label_5.setText(_translate("Yolowindow", "confidence threshold"))
        self.label_6.setText(_translate("Yolowindow", "NMS IOU threshold"))
        self.label_7.setText(_translate("Yolowindow", "FPS"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Yolowindow = QtWidgets.QMainWindow()
    ui = Ui_Yolowindow()
    ui.setupUi(Yolowindow)
    Yolowindow.show()
    sys.exit(app.exec_())
